---
- name: Configure Kubernetes Cluster on Rocky Linux 9
  hosts: "{{ target | default('all') }}"
  become: true
  roles:
    - common
    - containerd
    - kubernetes
  tags: [never, common]

- name: reload firewall on master
  hosts: master
  tasks:  
    - name: add firewall port
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 6443/tcp    # Kubernetes API
        - 2379-2380/tcp # etcd
        - 10250/tcp   # Kubelet API
        - 10259/tcp   # kube-scheduler
        - 10257/tcp   # kube-controller-manager
    - name: Reload firewalld for Kubernetes
      shell:
        firewall-cmd --reload
  tags: [never, master-config]
  
- name: Configure Kubernetes Master Nodes
  hosts: master
  become: true
  roles:
    - role-master-deploy
  tags: [never, master-config]

- name: reset Kubernetes Master Nodes
  hosts: "{{ target_hosts | default('all') }}" # Set default to 'all'
  become: yes
  vars_prompt:
    - name: target_hosts
      prompt: |
        Enter the host groups to remove (e.g., masters, workers, or all):
      private: no
  roles:
    - role-reset-node
  tags: [never, reset-node]

- name: share certificate
  hosts: k8s-m02, k8s-m03
  become: yes
  roles:
    - role: role-certificate-share
      vars:
        first_master: "{{ groups['master'][0] }}"
  tags: [never, cert-share]

- name: Get master join token
  hosts: master
  become: yes
  roles:
    - role: role-get-kubetoken
      vars:
        first_master: "{{ groups['master'][0] }}"
  tags: [never, worker-join]

- name: Provision Kubernetes HA Master Nodes
  hosts: master
  become: true
  roles:
    - role-master-join
  tags: [never, master-join]

- name: Configure Kubernetes Worker Nodes
  hosts: worker
  become: yes
  roles:
    - role-worker-join
  tags: [never, worker-join]

- name: Configure DNS on Rocky Linux 9
  hosts: all
  become: true
  vars:
    target_subnet: "192.168.1."
    new_nameserver: "10.96.0.10"
    new_search_domains: "default.svc.cluster.local;svc.cluster.local;cluster.local;lan"
  roles:
    - role-dns-update
  tags: [never, dns]

- name: Reset all the nodes
  hosts: worker, master
  become: yes
  roles:
    - role-remove-node
  tags: [never, remove-node]

- name: Deploy Monitoring Stack with Separate Namespaces
  hosts: localhost
  become: false
  roles:
    - role-calico-crd
  tags: [never, calico]

- name: Deploy Monitoring Stack with Separate Namespaces
  hosts: localhost
  become: false
  roles:
    - role-monitor-deploy
  vars:
    prometheus_namespace: prometheus
    grafana_namespace: grafana
    istio_namespace: istio-system
    storage_class: "standard"  # Update with your storage class
    helm_release_name: kube-prometheus-stack
    grafana_dashboards:
      - "3119"  # Kubernetes
      - "7630"  # Istio Mesh
      - "7636"  # Istio Service
      - "7639"  # Istio Workload
      - "13863" # Calico
  tags: [never, monitoring]

- name: Deploy metallb 
  hosts: localhost
  become: false
  roles:
    - role-metallb-deploy
  vars:
    metallb_version: "0.14.9"
  tags: [never, metallb]

- name: Create /data directory on all worker nodes
  hosts: worker  # Target worker nodes (change to "masters" if needed)     # Run tasks with sudo
  roles:
    - role-pvc-mgmt
  vars:
    data_dir: "/data"
    dir_mode: "0777"  # Set permissions (adjust as needed)
    dir_owner: "root"
    dir_group: "root"
    storage_size: 10Gi
    storage_class_name: hostpath-sc
    hostpath_directory: /data
    persistent_volume_reclaim_policy: Retain
    worker_nodes: "{{ groups['worker'] }}"
  tags: [never, worker-pvc]

- name: Configure Rocky 9 as Kubernetes GPU Worker
  hosts: k8s-s02
  become: yes
  vars:
    cuda_version: "12.2.2"
    nvidia_driver_version: "latest"
    k8s_version: "1.29"
    nvidia_device_plugin_version: "v0.14.5"
  roles:
    - role-gpu-config
  tags: [never, worker-gpu]

- name: Deploy NVIDIA Device Plugin (run on control plane)
  hosts: localhost
  become: no
  tasks:
    - name: Deploy NVIDIA device plugin
      command: kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/{{ nvidia_device_plugin_version }}/deployments/static/nvidia-device-plugin.yml
      when: inventory_hostname == "localhost"
  tags: [never, worker-gpu]