---
- name: Configure Kubernetes Cluster on Rocky Linux 9
  hosts: template
  become: true
  roles:
    - common
    - containerd
    - kubernetes
  tags: [never, template]

- name: Configure Kubernetes Master Nodes
  hosts: master
  become: true
  roles:
    - role-master-deploy
  tags: [never, master-config]

- name: Get master join token
  hosts: master
  become: yes
  roles:
    - role: role-get-kubetoken
      vars:
        first_master: "{{ groups['master'][0] }}"
  tags: [never, worker-join]

- name: Provision Kubernetes HA Master Nodes
  hosts: master
  become: true
  roles:
    - role-master-join
  tags: [never, master-join]

- name: Configure Kubernetes Worker Nodes
  hosts: worker
  become: yes
  roles:
    - role-worker-join
  tags: [never, worker-join]

- name: Reset all the nodes
  hosts: worker, master
  become: yes
  roles:
    - role-remove-node
  tags: [never, remove-node]
