---
- name: Configure firewall for Kubernetes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 6443/tcp    # Kubernetes API
    - 2379-2380/tcp # etcd
    - 10250/tcp   # Kubelet API
    - 10259/tcp   # kube-scheduler
    - 10257/tcp   # kube-controller-manager
- name: Reload firewalld for Kubernetes
  shell:
    firewall-cmd --reload

- name: Set first master
  set_fact:
    first_master: "{{ groups['master'][0] }}"

# roles/master/tasks/main.yml
- name: Create Kubernetes PKI directories on all master
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
  when: inventory_hostname != first_master

# roles/master/tasks/main.yml
- name: Ensure PKI directories exist on other master
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
  when: inventory_hostname != first_master

# k8s-file-transfer.yml

- name: Generate SSH key pair on first master
  openssh_keypair:
    path: /root/.ssh/id_rsa
    type: rsa
    size: 4096
    force: no
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname == groups['master'][0]

- name: Get public key content from first master
  shell: cat /root/.ssh/id_rsa.pub
  register: public_key_content
  run_once: true
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false

- name: Distribute public key to other master
  authorized_key:
    user: root
    state: present
    key: "{{ public_key_content.stdout }}"
  when: inventory_hostname != groups['master'][0]

- name: Create PKI directories on target master
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd
  when: inventory_hostname != first_master

- name: Initialize cluster on first master
  command: |
    kubeadm init \
      --control-plane-endpoint "{{ hostvars[first_master]['ansible_default_ipv4']['address'] }}" \
      --pod-network-cidr=10.10.0.0/16 \
      --upload-certs
#      --certificate-key "{{ lookup('password', '/dev/null length=32 chars=hex') }}" \
#      --token "{{ lookup('password', '/dev/null chars=hex,length=6') }}.{{ lookup('password', '/dev/null chars=hex,length=16') }}"
  when: inventory_hostname == first_master

- name: Copy kubeconfig to user directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    mode: 0600
  when: inventory_hostname == first_master

- name: Install Calico CNI
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  when: inventory_hostname == first_master

- name: Get join command
  command: kubeadm token create --print-join-command
  register: worker_join_cmd
  run_once: true
  when: inventory_hostname == first_master

- name: Extract control plane join command
  set_fact:
    control_plane_join_command: >-
      {{ worker_join_cmd.stdout | regex_search('kubeadm join .* --control-plane') }}
  when: inventory_hostname == first_master

