---
# roles/common/tasks/main.yml
- name: Set first master
  set_fact:
    first_master: "{{ groups['master'][0] }}"

- name: Debug worker_join_command in worker-join role
  debug:
    var: hostvars[groups['master'][0]].worker_join_command
  run_once: true

- name: Configure firewalld rules for Kubernetes
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
    zone: public
  loop:
    - { port: '6443/tcp' }       # Kubernetes API server
    - { port: '10250/tcp' }      # Kubelet API
    - { port: '30000-32767/tcp' } # NodePort services
    - { port: '8472/udp' }       # Flannel/Calico VXLAN
    - { port: '51820/udp' }      # Calico WireGuard
    - { port: '179/tcp' }        # Calico BGP (optional)


- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
  when: ansible_os_family == 'RedHat'

- name: Check if worker node has already joined the cluster
  command: kubectl get nodes -o jsonpath='{.items[*].metadata.name}'
  register: cluster_nodes
#  delegate_to: "{{ first_master }}"
  delegate_to: k8s-m01
  run_once: true
  changed_when: false

- name: Debug cluster nodes
  debug:
    msg: "Nodes in the cluster: {{ cluster_nodes.stdout }}"
  run_once: true
  delegate_to: k8s-m01

- name: Join worker to cluster (if not already joined)
  command: "{{ hostvars[groups['master'][0]].worker_join_command }}"
  register: join_result
  until: join_result.rc == 0
  retries: 5
  delay: 10
  when: >
    inventory_hostname not in cluster_nodes.stdout
  ignore_errors: yes
