# reset-k8s-nodes.yml
---
- name: Reset Kubernetes cluster configuration
  command: kubeadm reset -f
  ignore_errors: yes
  register: kubeadm_reset
  changed_when: "'successfully' in kubeadm_reset.stdout"
  
- name: Remove Kubernetes configuration directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/kubelet
    - /var/lib/etcd
    - "~/.kube"
  tags: [never, reset-node]
