---
- name: Set first master
  set_fact:
    first_master: "{{ groups['master'][0] }}"
- name: Get join command
  command: kubeadm token create --print-join-command
  register: worker_join_cmd
  run_once: true
  when: inventory_hostname == first_master

- name: Debug master_join_command in master-join role
  debug:
    var: hostvars[groups['master'][0]].worker_join_cmd
  run_once: true

- name: Extract control plane join command
  set_fact:
    control_plane_join_command: >-
      {{ worker_join_cmd.stdout }}{{ "--control-plane" }}
  when: inventory_hostname == first_master

- name: Debug master_join_command in worker-join role
  debug:
    var: hostvars[groups['master'][0]].control_plane_join_command
  run_once: true

- name: Check existing cluster nodes
  command: kubectl get nodes -o jsonpath='{.items[*].metadata.name}'
  register: existing_nodes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: yes
  changed_when: false

- name: Share control plane join command with other master
  set_fact:
    control_plane_join_command: "{{ hostvars[first_master]['control_plane_join_command'] }}"
  when: inventory_hostname != first_master

- name: Join other control plane nodes
  command: "{{ control_plane_join_command }}"
  register: join_result
  until: join_result.rc == 0
  retries: 3
  delay: 10
  when: 
    - inventory_hostname != groups['master'][0]
#    - inventory_hostname not in existing_nodes.stdout.split()
  ignore_errors: yes