# roles/master-join/tasks/main.yml
---
- name: Get join command
  command: kubeadm token create --print-join-command
  register: worker_join_cmd
  run_once: true
  when: inventory_hostname == first_master

- name: Print worker join command
  debug:
    msg: "{{ worker_join_cmd.stdout }}"
  run_once: true
  when: inventory_hostname == first_master

# roles/master-join/tasks/main.yml
- name: Set worker join command as a group variable
  set_fact:
    worker_join_command: "{{ worker_join_cmd.stdout }}"
  delegate_to: "{{ first_master }}"
  run_once: true

- name: Debug worker_join_command
  debug:
    var: worker_join_command
  run_once: true

