---
- name: Add Docker repository
  shell: |
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    dnf repolist
    dnf makecache

- name: Install containerd
  dnf:
    name: "containerd.io"
    state: present

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml

- name: Enable Systemd Cgroup Driver for containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true
